#!/bin/bash
#
#############
# CHANGELOG #
#############
#
# 2016-04-03 <fewbits> Creation of this script
# 2016-04-05 <fewbits> First useful version - 13 modules added and tested
#
########
# TODO #
########
#
# [!] Create the output file based on the hostname and current timestamp
# [X] Create repository in a local text file
# [X] Split repository entries by module
# [X] Execute each module (if it has at least one entry)
# [X] Sort and exclude repeated entries from the output file
# [X] Remove temporary files
# [_] Create syntax message
# [_] Create help message
# [_] Create option to reuse or force a new repository
#
#########
# FIXME #
#########
#
#
#
###############
# User Config #
###############
#
#
#
#################
# System Config #
#################
#
logFile="`hostname`.log"
repositoryFile="`hostname`.repository"
repositoryFileTemp="$repositoryFile.tmp"
moduleFileTemp="module.tmp"
inventoryFile="`hostname`.inventory"
inventoryFileTemp="$inventoryFile.tmp"
#
#############
# Functions #
#############

function logInfo() {
	#1 module
	#2 message
	
	echo "[`date +"%Y-%m-%d %H:%M:%S"`] [$1:info] $2" | tee -a $logFile
}

function logError() {
	#1 module
	#2 message
	#3 error code
	
	echo "[`date +"%Y-%m-%d %H:%M:%S"`] [$1:error] $2" | tee -a $logFile
	systemClean
	exit $3
}

function systemSplash() { # Display a Splash Screen
	echo
	echo "===> Welcome to fewbits/ibm-inventory tool <==="
	echo
	logInfo "system" "Starting tool"
}

function systemResults() { # Display the results of the tool
	logInfo "system" "Finishing tool"
	logInfo "system" "Repository file => $repositoryFile"
	logInfo "system" "Inventory file => $inventoryFile"
	logInfo "system" "Log file => $logFile"
}

function systemClean() { # Delete temporary files
	logInfo "system" "Deleting temporary files"
	rm -f $repositoryFileTemp
	rm -f $inventoryFileTemp
	rm -f $moduleFileTemp
}


function repositorySearch() { # Create the sources repository
	logInfo "repository" "Searching for IBM Software sources..."

	# Generating temp repository file
	find / \( -name "db2ls" -o -name "mqsiprofile" -o -name "InterchangeSystem.log" -o -name "idsversion" -o -name "imcl" -o -name "versioninfo.sh" -o -name "Version.xml" -o -name "de_lsrootiu.sh" -o -name "dspmqver" -o -name "nco_id" -o -name "FinalInstallInfo.txt" -o -name "versionInfo.sh" -o -name "fmcver" \) >> $repositoryFileTemp 2>/dev/null

	# Checking number of sources found
	repositoryCount=`cat $repositoryFileTemp | wc -l`
	
	# If 0, exit script with error
	if [ $repositoryCount -eq 0 ]; then
		logError "repository" "No sources has been found on this server. Check user and filesystem permissions, or maybe there is no software installed." 1
	# If 1 or more, continue
	else
		logInfo "repository" "Number of sources: $repositoryCount"
	fi

	sleep 1

	## Formatting repository file

	logInfo "repository" "Creating an empty repository file"
	> $repositoryFile
	
	# Header
	echo "# IBM Repository - Generated by fewbits/ibm-inventory.sh - Timestamp `date +'%Y-%m-%d %H:%M:%S'`" >> $repositoryFile
	echo >> $repositoryFile

}

function inventoryCreate() { # Create the inventory file
	logInfo "inventory" "Creating an empty inventory file"
	> $inventoryFile

	# Header	
	echo "# IBM Inventory - Generated by fewbits/ibm-inventory.sh - Timestamp `date +'%Y-%m-%d %H:%M:%S'`" >> $inventoryFile
	echo >> $inventoryFile

}

function inventoryFormat() { # Format the output of inventory file
	logInfo "inventory" "Formatting the inventory file"
	
	cat $inventoryFileTemp | sort | uniq >> $inventoryFile
}

function moduleCollect() {
	moduleName=$1		#1 Module name
	moduleFilter=$2		#2 Module filter for grep command
	moduleAction="$3"	#3 Module action after grep output

	logInfo "module" "Starting module => $moduleName"
	
	grep "$moduleFilter" $repositoryFileTemp | sort > $moduleFileTemp

	# Checking number of module entries
	moduleCount=`cat $moduleFileTemp | wc -l`

	# If 1 or more, continue
	if [ $moduleCount -gt 0 ]; then
		logInfo "module" "Number of entries: $moduleCount"
		sleep 1
		# Write to repository
		echo "[$moduleName]" >> $repositoryFile
		cat $moduleFileTemp >> $repositoryFile
		echo >> $repositoryFile
		# Write to inventory
		logInfo "module" "Collecting software..."
		while read repositoryEntry; do
			eval "$moduleAction"  >> $inventoryFileTemp
		done < $moduleFileTemp
		logInfo "module" "Done"
	# If 0, skip
	else
		logInfo "module" "No entries found. Skipping"
		sleep 1
	fi
	
}

##########
# Script #
##########

systemSplash
repositorySearch
inventoryCreate

## Modules - Begin ##
moduleCollect "Broker" "mqsiprofile" "\cat \$repositoryEntry | grep 'MQSI_VERSION=' | sed 's/MQSI_VERSION=//g' | while read version; do echo \"IBM WebSphere Message Broker \$version\"; done | sort -n | uniq"
moduleCollect "DB2" "db2ls" "\$repositoryEntry 2> /dev/null | egrep '^\/.*..:..:' | awk '{print \$2}' | while read version; do echo \"DB2 \$version\"; done | sort -n | uniq"
moduleCollect "DirectoryServer" "idsversion" "\$repositoryEntry 2>&1 > /dev/null | grep 'version:' | sed 's/ version:/ /g' | sort | uniq"
moduleCollect "ICS" "InterchangeSystem.log" "cat \$repositoryEntry | egrep '\[Version:' | cut -d] -f1 | cut -d: -f2 | while read version; do echo \"IBM WebSphere Interchange Server \$version\"; done | sort -n | uniq"
moduleCollect "InfoSphere" "Version.xml" "cat \$repositoryEntry | grep 'Product productId' | sed 's/^ *//g' | sed 's/<Product productId=\"//g' | sed 's/\" version=\"/ /g' | sed 's/\"\/>//g' | sort | uniq"
moduleCollect "InstallationManager" "imcl" "\$repositoryEntry listInstalledPackages -features -long 2> /dev/null | grep \"com.ibm\" | cut -d: -f3,4 | sed 's/^ *//g' | sed 's/ : / /g' | sort | uniq"
moduleCollect "MQ" "dspmqver" "\$repositoryEntry 2> /dev/null | egrep 'Name:|Version:' | sed 's/^Name://g' | sed 's/^Version:/|/g' | sed 'N;s/\n|//' | sed 's/^ *//g' | tr -s ' ' | sort | uniq"
moduleCollect "Netcool/Impact" "versioninfo.sh" "\$repositoryEntry 2> /dev/null | grep -i 'impact version' | tr ':' ' ' | tr -s ' ' | sort | uniq"
moduleCollect "Netcool/OMNIbus" "nco_id" "\$repositoryEntry 2> /dev/null | cut -d- -f1 | sort | uniq"
moduleCollect "Netcool/Reporter" "FinalInstallInfo.txt" "cat \$repositoryEntry | grep 'Netcool/Reporter' | sed 's/^ *//g'"
moduleCollect "WebSphere" "versionInfo.sh" "\$repositoryEntry 2> /dev/null | egrep '^Name  |^Version  ' | sed 's/^Name  //g' | sed 's/^Version  /|/g' | sed 'N;s/\n|//' | sed 's/^ *//g' | tr -s ' ' | sort | uniq"
moduleCollect "Workflow" "fmcver" "\$repositoryEntry | egrep '^Name:|^Version:|ServicePack:' | sed 's/^Name://g' | sed 's/^Version://g' | sed 's/^ServicePack://g' | sed 's/^ *//g' | tr -d '\n'; echo"
moduleCollect "de_lsrootiu" "de_lsrootiu.sh" "\$repositoryEntry 2> /dev/null |  egrep 'identityName|version' | grep -v "<?xml" | sed 's/^ *//g' | sed 's/<identityName>//g' | sed 's/<\/identityName>/|/g' | sed 's/<version>//g' | sed 's/<\/version>//g' | sed 'N;s/|\n/ /' | sed 's/\t//g' | sort | uniq"
## Modules - End ##

inventoryFormat
systemResults
systemClean

